name: Run Web Test
run-name: On Push
on: [push]

jobs:
  WebTest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Web Application
        run: docker run -d -p 8000:8000 vncrtech/puppybank

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12.2

      - name: Setup Workspace
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade robotframework-seleniumlibrary

      - name: Run RF WEB Test
        run: |
          robot -d ./resultados -v HEADLESS:true -v BROWSER:chromium TestesRobot
