
name: WebTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.12.2

      - name: Setup Web Application
        run: |
          python3 -m pip install robotframework && pip install robotframework-requests &&  pip install robotframework-seleniumlibrary \
          && pip install xvfbwrapper && pip install robotframework-xvfb && pip install certifi && pip install asn1crypto \
          && pip install bcrypt && pip install robotframework-sshlibrary && pip install cryptography && pip install pyOpenSSL \
          && pip install idna && pip install requests[security] && pip install --upgrade pip && pip install python-dev-tools


      - name: Verificar instalação
        run: |
          which google-chrome
          google-chrome --version
          which chromedriver
          chromedriver --version
      
      - name: Run RF WEB Test
        run: |
          robot -d ./resultados TestesRobot
