
name: WebTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options:
          --shm-size 2g

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libgconf-2-4
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Download and set up ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        wget -N http://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        rm chromedriver_linux64.zip

    - name: Run Robot Framework tests
      env:
        ROBOT_SYSLOG_LEVEL: TRACE
        ROBOT_OPTIONS: --loglevel TRACE
      run: |
        mkdir -p results
        robot --outputdir results TestesRobot

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: robot-results
        path: results
